# Generated by Django 4.1.13 on 2026-05-05 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('section', models.CharField(max_length=10)),
            ],
        ),
    ]
