# Generated by Django 4.1.13 on 2026-05-05 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=10)),
            ],
        ),
    ]
